from org.objectweb.asm import ClassWriter, Opcodes, Label
from java.lang import ClassLoader
from lib.asm import CustomClassLoader, initClass, initMethod, initMethodObj
from java.lang import Integer, Math, Double

def definePixels(classname=None):
  if classname is None:
    classname = "asm/pixels/Pixels"
  
  classWriter = initClass(classname)

  methodVisitor = classWriter.visitMethod(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                                          "enhancedMinAndMax", "(Lij/process/ShortProcessor;I)V", None, None)
  methodVisitor.visitCode()
  label0 = Label()
  methodVisitor.visitLabel(label0)
  methodVisitor.visitLineNumber(10, label0)
  methodVisitor.visitVarInsn(Opcodes.ALOAD, 0)
  methodVisitor.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "ij/process/ShortProcessor", "getPixels", "()Ljava/lang/Object;", False)
  methodVisitor.visitTypeInsn(Opcodes.CHECKCAST, "[S")
  methodVisitor.visitTypeInsn(Opcodes.CHECKCAST, "[S")
  methodVisitor.visitVarInsn(Opcodes.ASTORE, 2)
  label1 = Label()
  methodVisitor.visitLabel(label1)
  methodVisitor.visitLineNumber(12, label1)
  methodVisitor.visitVarInsn(Opcodes.ALOAD, 2)
  methodVisitor.visitInsn(Opcodes.ARRAYLENGTH)
  methodVisitor.visitIntInsn(Opcodes.NEWARRAY, Opcodes.T_INT)
  methodVisitor.visitVarInsn(Opcodes.ASTORE, 3)
  label2 = Label()
  methodVisitor.visitLabel(label2)
  methodVisitor.visitLineNumber(13, label2)
  methodVisitor.visitInsn(Opcodes.LCONST_0)
  methodVisitor.visitVarInsn(Opcodes.LSTORE, 4)
  label3 = Label()
  methodVisitor.visitLabel(label3)
  methodVisitor.visitLineNumber(14, label3)
  methodVisitor.visitInsn(Opcodes.ICONST_0)
  methodVisitor.visitVarInsn(Opcodes.ISTORE, 6)
  label4 = Label()
  methodVisitor.visitLabel(label4)
  methodVisitor.visitLineNumber(15, label4)
  methodVisitor.visitInsn(Opcodes.ICONST_0)
  methodVisitor.visitVarInsn(Opcodes.ISTORE, 7)
  label5 = Label()
  methodVisitor.visitLabel(label5)
  methodVisitor.visitFrame(Opcodes.F_FULL, 7, ["ij/process/ShortProcessor", Opcodes.INTEGER, "[S", "[I", Opcodes.LONG, Opcodes.INTEGER, Opcodes.INTEGER], 0, [])
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
  methodVisitor.visitVarInsn(Opcodes.ALOAD, 2)
  methodVisitor.visitInsn(Opcodes.ARRAYLENGTH)
  label6 = Label()
  methodVisitor.visitJumpInsn(Opcodes.IF_ICMPGE, label6)
  label7 = Label()
  methodVisitor.visitLabel(label7)
  methodVisitor.visitLineNumber(16, label7)
  methodVisitor.visitVarInsn(Opcodes.ALOAD, 2)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 7)
  methodVisitor.visitInsn(Opcodes.SALOAD)
  methodVisitor.visitLdcInsn(Integer(65535))
  methodVisitor.visitInsn(Opcodes.IAND)
  methodVisitor.visitVarInsn(Opcodes.ISTORE, 8)
  label8 = Label()
  methodVisitor.visitLabel(label8)
  methodVisitor.visitLineNumber(17, label8)
  methodVisitor.visitInsn(Opcodes.ICONST_0)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 8)
  label9 = Label()
  methodVisitor.visitJumpInsn(Opcodes.IF_ICMPNE, label9)
  label10 = Label()
  methodVisitor.visitJumpInsn(Opcodes.GOTO, label10)
  methodVisitor.visitLabel(label9)
  methodVisitor.visitLineNumber(18, label9)
  methodVisitor.visitFrame(Opcodes.F_APPEND,1, [Opcodes.INTEGER], 0, None)
  methodVisitor.visitVarInsn(Opcodes.ALOAD, 3)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
  methodVisitor.visitIincInsn(6, 1)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 8)
  methodVisitor.visitInsn(Opcodes.IASTORE)
  label11 = Label()
  methodVisitor.visitLabel(label11)
  methodVisitor.visitLineNumber(19, label11)
  methodVisitor.visitVarInsn(Opcodes.LLOAD, 4)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 8)
  methodVisitor.visitInsn(Opcodes.I2L)
  methodVisitor.visitInsn(Opcodes.LADD)
  methodVisitor.visitVarInsn(Opcodes.LSTORE, 4)
  methodVisitor.visitLabel(label10)
  methodVisitor.visitLineNumber(15, label10)
  methodVisitor.visitFrame(Opcodes.F_CHOP,1, None, 0, None)
  methodVisitor.visitIincInsn(7, 1)
  methodVisitor.visitJumpInsn(Opcodes.GOTO, label5)
  methodVisitor.visitLabel(label6)
  methodVisitor.visitLineNumber(22, label6)
  methodVisitor.visitFrame(Opcodes.F_CHOP,1, None, 0, None)
  methodVisitor.visitVarInsn(Opcodes.LLOAD, 4)
  methodVisitor.visitInsn(Opcodes.L2D)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitInsn(Opcodes.DDIV)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 7)
  label12 = Label()
  methodVisitor.visitLabel(label12)
  methodVisitor.visitLineNumber(24, label12)
  methodVisitor.visitInsn(Opcodes.DCONST_0)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 9)
  label13 = Label()
  methodVisitor.visitLabel(label13)
  methodVisitor.visitLineNumber(25, label13)
  methodVisitor.visitInsn(Opcodes.ICONST_0)
  methodVisitor.visitVarInsn(Opcodes.ISTORE, 11)
  label14 = Label()
  methodVisitor.visitLabel(label14)
  methodVisitor.visitFrame(Opcodes.F_APPEND,3, [Opcodes.DOUBLE, Opcodes.DOUBLE, Opcodes.INTEGER], 0, None)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 11)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
  label15 = Label()
  methodVisitor.visitJumpInsn(Opcodes.IF_ICMPGE, label15)
  label16 = Label()
  methodVisitor.visitLabel(label16)
  methodVisitor.visitLineNumber(26, label16)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 9)
  methodVisitor.visitVarInsn(Opcodes.ALOAD, 3)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 11)
  methodVisitor.visitInsn(Opcodes.IALOAD)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 7)
  methodVisitor.visitInsn(Opcodes.DSUB)
  methodVisitor.visitLdcInsn(Double("2.0"))
  methodVisitor.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Math", "pow", "(DD)D", False)
  methodVisitor.visitInsn(Opcodes.DADD)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 9)
  label17 = Label()
  methodVisitor.visitLabel(label17)
  methodVisitor.visitLineNumber(25, label17)
  methodVisitor.visitIincInsn(11, 1)
  methodVisitor.visitJumpInsn(Opcodes.GOTO, label14)
  methodVisitor.visitLabel(label15)
  methodVisitor.visitLineNumber(28, label15)
  methodVisitor.visitFrame(Opcodes.F_CHOP,1, None, 0, None)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 9)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitInsn(Opcodes.DDIV)
  methodVisitor.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Math", "sqrt", "(D)D", False)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 11)
  label18 = Label()
  methodVisitor.visitLabel(label18)
  methodVisitor.visitLineNumber(30, label18)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 7)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 1)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 11)
  methodVisitor.visitInsn(Opcodes.DMUL)
  methodVisitor.visitInsn(Opcodes.DSUB)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 13)
  label19 = Label()
  methodVisitor.visitLabel(label19)
  methodVisitor.visitLineNumber(31, label19)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 7)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 1)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 11)
  methodVisitor.visitInsn(Opcodes.DMUL)
  methodVisitor.visitInsn(Opcodes.DADD)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 15)
  label20 = Label()
  methodVisitor.visitLabel(label20)
  methodVisitor.visitLineNumber(33, label20)
  methodVisitor.visitLdcInsn(Double("2.147483647E9"))
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 17)
  label21 = Label()
  methodVisitor.visitLabel(label21)
  methodVisitor.visitLineNumber(34, label21)
  methodVisitor.visitInsn(Opcodes.DCONST_0)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 19)
  label22 = Label()
  methodVisitor.visitLabel(label22)
  methodVisitor.visitLineNumber(35, label22)
  methodVisitor.visitInsn(Opcodes.ICONST_0)
  methodVisitor.visitVarInsn(Opcodes.ISTORE, 21)
  label23 = Label()
  methodVisitor.visitLabel(label23)
  methodVisitor.visitFrame(Opcodes.F_FULL, 14, ["ij/process/ShortProcessor", Opcodes.INTEGER, "[S", "[I", Opcodes.LONG, Opcodes.INTEGER, Opcodes.DOUBLE, Opcodes.DOUBLE, Opcodes.DOUBLE, Opcodes.DOUBLE, Opcodes.DOUBLE, Opcodes.DOUBLE, Opcodes.DOUBLE, Opcodes.INTEGER], 0, [])
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 21)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 6)
  label24 = Label()
  methodVisitor.visitJumpInsn(Opcodes.IF_ICMPGE, label24)
  label25 = Label()
  methodVisitor.visitLabel(label25)
  methodVisitor.visitLineNumber(36, label25)
  methodVisitor.visitVarInsn(Opcodes.ALOAD, 3)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 21)
  methodVisitor.visitInsn(Opcodes.IALOAD)
  methodVisitor.visitVarInsn(Opcodes.ISTORE, 22)
  label26 = Label()
  methodVisitor.visitLabel(label26)
  methodVisitor.visitLineNumber(37, label26)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 22)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 17)
  methodVisitor.visitInsn(Opcodes.DCMPG)
  label27 = Label()
  methodVisitor.visitJumpInsn(Opcodes.IFGE, label27)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 22)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 13)
  methodVisitor.visitInsn(Opcodes.DCMPL)
  methodVisitor.visitJumpInsn(Opcodes.IFLE, label27)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 22)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 17)
  methodVisitor.visitLabel(label27)
  methodVisitor.visitLineNumber(38, label27)
  methodVisitor.visitFrame(Opcodes.F_APPEND,1, [Opcodes.INTEGER], 0, None)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 22)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 19)
  methodVisitor.visitInsn(Opcodes.DCMPL)
  label28 = Label()
  methodVisitor.visitJumpInsn(Opcodes.IFLE, label28)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 22)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 15)
  methodVisitor.visitInsn(Opcodes.DCMPG)
  methodVisitor.visitJumpInsn(Opcodes.IFGE, label28)
  methodVisitor.visitVarInsn(Opcodes.ILOAD, 22)
  methodVisitor.visitInsn(Opcodes.I2D)
  methodVisitor.visitVarInsn(Opcodes.DSTORE, 19)
  methodVisitor.visitLabel(label28)
  methodVisitor.visitLineNumber(35, label28)
  methodVisitor.visitFrame(Opcodes.F_CHOP,1, None, 0, None)
  methodVisitor.visitIincInsn(21, 1)
  methodVisitor.visitJumpInsn(Opcodes.GOTO, label23)
  methodVisitor.visitLabel(label24)
  methodVisitor.visitLineNumber(40, label24)
  methodVisitor.visitFrame(Opcodes.F_CHOP,1, None, 0, None)
  methodVisitor.visitVarInsn(Opcodes.ALOAD, 0)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 17)
  methodVisitor.visitVarInsn(Opcodes.DLOAD, 19)
  methodVisitor.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "ij/process/ShortProcessor", "setMinAndMax", "(DD)V", False)
  label29 = Label()
  methodVisitor.visitLabel(label29)
  methodVisitor.visitLineNumber(41, label29)
  methodVisitor.visitInsn(Opcodes.RETURN)
  methodVisitor.visitMaxs(6, 23)
  methodVisitor.visitEnd()

  classWriter.visitEnd()

  loader = CustomClassLoader()
  Pixels = loader.defineClass(classname, classWriter.toByteArray())
  return Pixels

Pixels = definePixels()
